### ISSUE TITLE
React warnings for unique key prop

### ISSUE THREAD

**Issue by janczizikow** [escaladesports/gatsby-plugin-polyfill-io#1]
After including the plugin in my project I got required key props warning in the console:

```
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the top-level render call using <body>. See https://fb.me/react-warning-keys for more information.
    in script
    in HTML
```
[https://reactjs.org/docs/lists-and-keys.html#keys](https://reactjs.org/docs/lists-and-keys.html#keys)

I'm using next beta version of Gatsby (`^2.0.0-rc.13`) and the `^1.0.4` version of the plugin. 

I guess this warning is not really that important as the <script> tag isn't controlled through React, but would there be a way to get around it?

**Comment by kennedyrose** [comment]
Fixed with https://github.com/escaladesports/gatsby-plugin-polyfill-io/commit/7db4cca08f678293d6229603bf7d1610476c8cc8

**Comment by janczizikow** [comment]
Awesome thanks a lot for the fix and cool plugin 👍
